# Generated by Django 6.0.1 on 2026-01-16 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_masterprofile_address_favoritemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В процессе'), ('done', 'Готово')], default='todo', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='users.masterprofile', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['master', 'date'], name='todo_todoit_master__cc0b91_idx'), models.Index(fields=['master', 'status'], name='todo_todoit_master__c4f016_idx')],
            },
        ),
    ]
