# Generated by Django 5.0.1 on 2026-01-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_initial"),
        ("services", "0004_add_custom_service_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="master_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="services.masterservice",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="services.service",
            ),
        ),
    ]
