# Generated by Django 5.0.1 on 2026-02-04 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_add_is_archived_to_appointment"),
        ("services", "0004_add_custom_service_support"),
        ("users", "0003_add_coordinates_to_master"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["master", "date", "status"], name="appointment_master__e64005_idx"
            ),
        ),
    ]
