# Generated by Django 6.0.1 on 2026-04-05 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_materials'),
        ('users', '0008_remove_masterprofile_accept_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Заметка о клиенте')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_notes_about_me', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='users.masterprofile')),
            ],
            options={
                'verbose_name': 'Заметка о клиенте',
                'verbose_name_plural': 'Заметки о клиентах',
                'ordering': ['-updated_at'],
                'unique_together': {('master', 'client')},
            },
        ),
    ]
