# Generated by Django 6.0.1 on 2026-01-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='users.masterprofile'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category'),
        ),
        migrations.AddField(
            model_name='masterservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='services.service'),
        ),
        migrations.AlterUniqueTogether(
            name='masterservice',
            unique_together={('master', 'service')},
        ),
    ]
