# Generated by Django 5.0.1 on 2026-01-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_portfolioitem"),
        ("users", "0002_masterprofile_address_favoritemaster"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="masterservice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category for custom services",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_master_services",
                to="services.category",
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="custom_description",
            field=models.TextField(blank=True, help_text="Custom service description"),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="custom_name",
            field=models.CharField(
                blank=True,
                help_text="Custom service name (for services not in catalog)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price (overrides catalog service price or sets for custom)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to catalog service (optional for custom services)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masters",
                to="services.service",
            ),
        ),
        migrations.AddConstraint(
            model_name="masterservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False)),
                fields=("master", "service"),
                name="unique_master_catalog_service",
            ),
        ),
    ]
