# Generated by Django 5.0.1 on 2026-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_add_portfolio_like"),
        ("users", "0007_add_consent_version_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="masterservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_name__gt", ""), ("service__isnull", True)),
                fields=("master", "custom_name"),
                name="unique_master_custom_service",
            ),
        ),
    ]
