# Generated by Django 6.0.1 on 2026-01-12 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='FavoriteMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='users.masterprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_masters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный мастер',
                'verbose_name_plural': 'Избранные мастера',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'master')},
            },
        ),
    ]
