# Generated by Django 6.0.1 on 2026-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_coordinates_to_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='accept_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='accept_sbp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='accept_yoomoney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='online_payments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='prepayment_percent',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='prepayment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='reminder_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='vk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
