# Generated by Django 6.0.1 on 2026-03-29 21:44

import string
import random

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generate_referral_codes(apps, schema_editor):
    """Generate unique referral codes for existing users."""
    User = apps.get_model('users', 'User')
    chars = string.ascii_uppercase + string.digits
    existing_codes = set()
    for user in User.objects.all():
        while True:
            code = ''.join(random.choices(chars, k=8))
            if code not in existing_codes:
                existing_codes.add(code)
                user.referral_code = code
                user.save(update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_early_adopter',
            field=models.BooleanField(default=False, verbose_name='Ранний пользователь (бесплатный Pro)'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Реферальный код'),
        ),
        migrations.RunPython(generate_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил'),
        ),
    ]
