# Generated by Django 6.0.1 on 2026-04-05 09:46

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_consent_version_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='accept_card',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='accept_sbp',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='accept_yoomoney',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='online_payments_enabled',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='prepayment_percent',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='prepayment_required',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='rebooking_reminder_days',
            field=models.PositiveIntegerField(default=0, help_text='Через сколько дней напомнить клиенту о повторной записи (0 = выключено)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path),
        ),
    ]
