# Generated by Django 5.0.1 on 2026-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_masterprofile_accept_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterprofile",
            name="tax_system",
            field=models.CharField(
                choices=[
                    ("none", "Не указано"),
                    ("self_employed", "Самозанятый (НПД)"),
                    ("ip_usn6", "ИП УСН 6%"),
                    ("ip_usn15", "ИП УСН 15%"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
