# Generated by Django 6.0.1 on 2026-01-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_new', 'Новая запись'), ('appointment_confirmed', 'Запись подтверждена'), ('appointment_cancelled', 'Запись отменена'), ('appointment_rescheduled', 'Запись перенесена'), ('appointment_reminder', 'Напоминание о записи'), ('appointment_completed', 'Запись завершена'), ('review_new', 'Новый отзыв'), ('payment_received', 'Платёж получен'), ('payment_refunded', 'Возврат платежа'), ('system', 'Системное')], default='system', max_length=30),
        ),
    ]
