# Generated by Django 6.0.1 on 2026-03-29 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_type', models.CharField(choices=[('free_month_pro', 'Бесплатный месяц Pro')], default='free_month_pro', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('applied', 'Применено'), ('expired', 'Истекло')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённый')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
    ]
