# Generated by Django 6.0.1 on 2026-04-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_referral_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='yookassa_payment_method_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='tbank_rebill_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='client_notes_enabled',
            field=models.BooleanField(default=False, help_text='Заметки о клиентах (мини-CRM)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='client_stats_enabled',
            field=models.BooleanField(default=False, help_text='Доступ к статистике расходов'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='extended_search',
            field=models.BooleanField(default=False, help_text='Расширенные фильтры поиска мастеров'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='history_months',
            field=models.PositiveIntegerField(default=3, help_text='Кол-во месяцев истории записей (0 = без ограничений)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_favorites',
            field=models.PositiveIntegerField(default=5, help_text='Макс. избранных мастеров (0 = без ограничений)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_pinned_portfolio',
            field=models.PositiveIntegerField(default=0, help_text='Макс. закреплённых работ в портфолио (0 = нельзя)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pro_badge',
            field=models.BooleanField(default=False, help_text='Бейдж PRO в профиле мастера'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='rebooking_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Автоматические напоминания клиентам о повторной записи'),
        ),
    ]
