# Generated by Django 5.0.1 on 2026-04-09 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chatmessage_reply_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="hidden_for",
            field=models.ManyToManyField(
                blank=True,
                related_name="hidden_chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Скрыт для",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat", "is_read", "-created_at"], name="chat_chatme_chat_id_04e761_idx"
            ),
        ),
    ]
