# Generated by Django 6.0.1 on 2026-01-12 10:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutDestination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_type', models.CharField(choices=[('card', 'Банковская карта'), ('yoomoney', 'ЮMoney'), ('bank_account', 'Расчётный счёт')], max_length=20)),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('card_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип карты (Visa, MC, МИР)')),
                ('yoomoney_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Счёт ЮMoney')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название банка')),
                ('bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер счёта')),
                ('payout_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен для выплаты')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_destinations', to='users.masterprofile')),
            ],
            options={
                'verbose_name': 'Способ вывода',
                'verbose_name_plural': 'Способы вывода',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Доступный баланс')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='В ожидании (холд)')),
                ('hold_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Заморожено')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Всего заработано')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Всего выведено')),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Комиссия платформы')),
                ('auto_withdraw', models.BooleanField(default=False, verbose_name='Автовывод')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.masterprofile')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))], verbose_name='Сумма вывода')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Комиссия за вывод')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма к получению')),
                ('method', models.CharField(choices=[('card', 'На карту'), ('yoomoney', 'ЮMoney'), ('bank_account', 'Расчётный счёт')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Выполнен'), ('rejected', 'Отклонён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры карты')),
                ('destination_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Счёт получателя')),
                ('external_payout_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID выплаты в платёжной системе')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Запрос на вывод',
                'verbose_name_plural': 'Запросы на вывод',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('prepayment', 'Предоплата'), ('full_payment', 'Полная оплата'), ('remaining', 'Доплата'), ('tip', 'Чаевые')], default='full_payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'Обрабатывается'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('partially_refunded', 'Частичный возврат'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('yoomoney', 'ЮMoney'), ('cash', 'Наличные')], max_length=20, null=True)),
                ('payment_provider', models.CharField(choices=[('yookassa', 'YooKassa'), ('tinkoff', 'Тинькофф'), ('sberbank', 'Сбербанк'), ('manual', 'Ручной ввод')], default='yookassa', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Сумма платежа')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Комиссия платформы')),
                ('provider_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Комиссия провайдера')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма к выплате мастеру')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Возвращённая сумма')),
                ('external_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='ID платежа в платёжной системе')),
                ('confirmation_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('payment_metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные платежа')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('available_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступности средств')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_payments', to='users.masterprofile')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'), models.Index(fields=['client', 'status'], name='payments_pa_client__39a683_idx'), models.Index(fields=['master', 'status'], name='payments_pa_master__6dcab0_idx')],
            },
        ),
    ]
