# Generated by Django 5.0.1 on 2026-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["wallet", "status"], name="payments_wi_wallet__123f0f_idx"),
        ),
    ]
